### PR TITLE
adds nodemon dev dependency & adds watch script to use nodemon

### PR DESCRIPTION
**Pull request by maxohsawa**
adds nodemon dev dep & adds watch script. npm run watch correctly launches server without error.

### CODE REVIEW

**Comment by benjaminbwright** [comment]
Hey Max. It looks like there are conflicts. Maybe just delete the package-lock.json, ignore it and run an npm i again. Otherwise, should be good.

**Comment by maxohsawa** [comment]
Thanks for the suggestion! I added package-lock to gitignore and removed package-lock from git tracked files. Re-committed and ready to have looked again.

**Comment by maxohsawa** [comment]
I think I did it

**Review by benjaminbwright — APPROVED** [review]
Great. Looks good.

**Pull request merged**
